<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Agent</name>
   <tag></tag>
   <elementGuidId>cab0f75f-3027-4759-bab1-6fa7910a12cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-cxa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='select-cxa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Agent&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04d92efb-b389-45d7-8ef0-42247f9a3a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>8ccc725c-4ade-41cd-8700-5138bfeab460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d33af66f-a2cc-434f-a6b6-c0e070487b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-item-row ng-tns-c967170128-2 top-module-button ng-star-inserted</value>
      <webElementGuid>4c47f919-99eb-420b-9730-17dbe28834bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-cxa</value>
      <webElementGuid>0f0b74b9-e63e-4523-a98a-e86d0c609de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Agent</value>
      <webElementGuid>1d5e1970-08dd-48c2-9e5b-51f385dec721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agent</value>
      <webElementGuid>ae33fc2e-aefd-46eb-96ca-eac5d9dc5974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-cxa&quot;)</value>
      <webElementGuid>1029f59d-ee9d-42fb-8f5d-c7810e8b0cac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='select-cxa']</value>
      <webElementGuid>180af70f-6092-4e1a-b855-3814f37798b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAX'])[1]/following::a[1]</value>
      <webElementGuid>281fc85d-c285-4458-af3b-d684a6727b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OMNICHANNEL ROUTING'])[1]/following::a[2]</value>
      <webElementGuid>c4089189-4f75-441e-a90d-90b2ea52440d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WORKFORCE ENGAGEMENT'])[1]/preceding::a[1]</value>
      <webElementGuid>42685e2a-b2ae-41dd-b4ab-75f94467f1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>3552442a-1689-4af7-8bb7-85ab4e4ff222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'select-cxa' and (text() = 'Agent' or . = 'Agent')]</value>
      <webElementGuid>4acdb072-66fe-492e-b1c8-620fa8ce187e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
