<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MAX</name>
   <tag></tag>
   <elementGuidId>c8ce4147-676b-477c-aa5c-0942333536c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.module-name.ng-tns-c967170128-2.max.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='select-max']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;MAX&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1d844de5-0a34-49e8-a258-3a031c5c7b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>module-name ng-tns-c967170128-2 max ng-star-inserted</value>
      <webElementGuid>6b327720-8fcc-4cde-b3e5-7be1d986cd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MAX</value>
      <webElementGuid>c7082687-e3ed-4a20-adb1-fa6e6ddf971f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-max&quot;)/div[@class=&quot;module-name ng-tns-c967170128-2 max ng-star-inserted&quot;]</value>
      <webElementGuid>e5ccba53-c4f1-49aa-bda1-e0f24a0ae8b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='select-max']/div</value>
      <webElementGuid>fff0fcfe-3280-4a7a-be36-bc4be417fb66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OMNICHANNEL ROUTING'])[1]/following::div[2]</value>
      <webElementGuid>73fc6d9b-492d-4c0b-8d02-d8323b314f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applications'])[1]/following::div[7]</value>
      <webElementGuid>d3ca97ee-1e62-413e-83e0-cd5dc51f710e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agent'])[1]/preceding::div[3]</value>
      <webElementGuid>dfa8aaff-2885-4843-90f5-9315c8ee2478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>d9ff2b6e-c34e-4bfa-90ed-c4763f2fdeed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'MAX' or . = 'MAX')]</value>
      <webElementGuid>0ac3e4e2-db50-40c0-a933-0da0f6ed10ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
