<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Agent</name>
   <tag></tag>
   <elementGuidId>7c04c82d-7f58-4d5c-8793-5f9dff170ebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.module-name.ng-tns-c967170128-2.cxa.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='select-cxa']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Agent&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e2f5108c-c11f-4e34-a934-cfa4f4c2d0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>module-name ng-tns-c967170128-2 cxa ng-star-inserted</value>
      <webElementGuid>52a25639-7748-4758-be52-1bf9056539a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agent</value>
      <webElementGuid>93a37b41-860c-41ff-9b58-e29cf6fb46c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-cxa&quot;)/div[@class=&quot;module-name ng-tns-c967170128-2 cxa ng-star-inserted&quot;]</value>
      <webElementGuid>d6397a73-df45-4596-bc81-9fe433e07709</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='select-cxa']/div</value>
      <webElementGuid>a99015b0-7d17-4cdf-a523-f5a44186f65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAX'])[1]/following::div[3]</value>
      <webElementGuid>0862d61e-7a4f-44f8-ae7b-bbbbd756698f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OMNICHANNEL ROUTING'])[1]/following::div[5]</value>
      <webElementGuid>ac5ebc6b-03e9-437f-b18c-68c1a4f6a5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WORKFORCE ENGAGEMENT'])[1]/preceding::div[3]</value>
      <webElementGuid>e03e2771-2b19-4ed2-aa50-2548937d5abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div</value>
      <webElementGuid>64ca3a9b-06f7-4074-a2f2-dd21fc34eb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Agent' or . = 'Agent')]</value>
      <webElementGuid>6304b424-8127-46e5-8826-d833bd9619b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
