<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Agent</name>
   <tag></tag>
   <elementGuidId>227345be-4a72-4405-abc5-a037bcb852a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.module-name.ng-tns-c967170128-2.cxa.ng-star-inserted > span.ng-tns-c967170128-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='select-cxa']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Agent&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c8cfa87c-c91b-49a9-8844-87f85cb5ba6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>containerclass</name>
      <type>Main</type>
      <value>cxone-tooltip-container</value>
      <webElementGuid>62614c01-9e1f-4a7c-956b-bc85db3edec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>3d62a52a-5bad-4593-8c00-59cb87a4e803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c967170128-2</value>
      <webElementGuid>e0e14504-16c5-4097-8599-7691e2b0bc27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip-6</value>
      <webElementGuid>4a9c4654-e95f-49f8-8c97-a887e6944fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agent</value>
      <webElementGuid>1e525ce7-b5e7-47b9-b040-a74f2761dc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-cxa&quot;)/div[@class=&quot;module-name ng-tns-c967170128-2 cxa ng-star-inserted&quot;]/span[@class=&quot;ng-tns-c967170128-2&quot;]</value>
      <webElementGuid>3980cc04-2117-431c-b84e-e4804fee90ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='select-cxa']/div/span</value>
      <webElementGuid>21f74e1b-e197-4487-9866-b0df6aa00334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAX'])[1]/following::span[1]</value>
      <webElementGuid>484a37f2-7a93-4dfd-b64e-300f6ef837b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OMNICHANNEL ROUTING'])[1]/following::span[2]</value>
      <webElementGuid>149602cd-24e0-4826-97b1-65f2e0a2a3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agent'])[2]/preceding::span[1]</value>
      <webElementGuid>096f1a9e-7cdd-405c-902c-079436943ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WORKFORCE ENGAGEMENT'])[1]/preceding::span[1]</value>
      <webElementGuid>c0e3f2c3-291b-4f9b-99d9-d1b6a9752a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agent']/parent::*</value>
      <webElementGuid>f35ea4d5-08cd-41b4-a6da-10dded0dd94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/span</value>
      <webElementGuid>77ebaeeb-7d93-41f0-b6e0-93e348a5e933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Agent' or . = 'Agent')]</value>
      <webElementGuid>76a3b4cd-5974-4a5e-bdf5-bbec34acbd05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
