<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Call</name>
   <tag></tag>
   <elementGuidId>32323cf9-9c97-4feb-87f1-3989d3cbfb2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.call</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='abEntry_searchexternalresult']/div[2]/div/span/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Call&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ccdc5e21-9840-4af4-84fc-dfee4ab95666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>[title]Call;Call</value>
      <webElementGuid>ab2820b3-39f7-40c4-8b47-7cb116ded309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>call</value>
      <webElementGuid>e4dccd86-82ba-413a-9411-d79be4f26975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-media-type-id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6e9240a4-3e98-461e-9a6d-824076abb71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Call</value>
      <webElementGuid>8c340a58-08b2-427c-b07a-644b60d8d288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Call</value>
      <webElementGuid>29027391-a61c-4be0-a19a-d54ebd80d3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abEntry_searchexternalresult&quot;)/div[@class=&quot;entry left&quot;]/div[@class=&quot;call-controls&quot;]/span[@class=&quot;contact-info-custom&quot;]/button[@class=&quot;call&quot;]</value>
      <webElementGuid>085f8534-4427-4494-a720-c0c424caca0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='abEntry_searchexternalresult']/div[2]/div/span/button</value>
      <webElementGuid>0fda167d-d020-453d-aa63-b5f2774b3be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NaN days'])[1]/following::button[1]</value>
      <webElementGuid>8b66ded1-2f60-4c54-ac49-f8f85120c773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='External'])[1]/following::button[1]</value>
      <webElementGuid>223e1e86-98da-4dd8-a9ea-54447e2c1c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMS'])[2]/preceding::button[1]</value>
      <webElementGuid>cdc6ed84-e631-48bc-8a8b-3c6c3800b069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No outbound skill'])[2]/preceding::button[2]</value>
      <webElementGuid>8056d18a-f073-42f5-8322-554fed15569f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>16b90ad4-8835-41cf-bd25-119dc8ddff0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Call' and (text() = 'Call' or . = 'Call')]</value>
      <webElementGuid>15858890-711b-46fd-a7b6-40a110a20f2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
