<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Call History</name>
   <tag></tag>
   <elementGuidId>45cfccb6-18cc-4935-8d43-49179cbe5c84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.call-history-container > h2.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='personalqueueui-0']/div[2]/div[3]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Call History&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>8880a151-a314-4191-ba9e-6956099fe731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>468cb6d2-c80f-4fa6-bec0-c114ff1b4a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>[title]CallHistory;CallHistory</value>
      <webElementGuid>7e792b70-01c7-4b03-8c24-f9db014936ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Call History</value>
      <webElementGuid>ccc380f5-13ff-4ee4-88f7-c677820cc325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Call History</value>
      <webElementGuid>dfa5421d-a91d-4508-a7fe-d6931ff0336b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personalqueueui-0&quot;)/div[@class=&quot;personal-queue-background&quot;]/div[@class=&quot;call-history-container&quot;]/h2[@class=&quot;title&quot;]</value>
      <webElementGuid>16a4c961-90d0-413f-915d-ebbf9a7c431c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personalqueueui-0']/div[2]/div[3]/h2</value>
      <webElementGuid>b0b18f3d-161c-424c-a790-5e6a687417cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open WEM'])[1]/following::h2[1]</value>
      <webElementGuid>bc19da60-d0f0-40c4-8411-57b1597e6e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have no scheduled events today.'])[1]/following::h2[1]</value>
      <webElementGuid>5888d22d-e408-49bd-a81e-4d4163a03096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have no recent calls logged.'])[1]/preceding::h2[1]</value>
      <webElementGuid>99f35fe0-d944-4571-b527-d29ec24e7777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outboundcalls_US'])[4]/preceding::h2[1]</value>
      <webElementGuid>171e1c2d-1c68-4963-80f5-0bb0296ca2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Call History']/parent::*</value>
      <webElementGuid>0a9bf0c8-08cd-4204-be3b-4f86901af3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/h2</value>
      <webElementGuid>3b959ad9-b28b-40e3-8719-09617fd23426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@title = 'Call History' and (text() = 'Call History' or . = 'Call History')]</value>
      <webElementGuid>9df547a0-84fc-4c25-9571-ea26f089446d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
