<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_010</name>
   <tag></tag>
   <elementGuidId>63e40532-e1ef-4fa8-85ac-0811dfcc265d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.contact-state-info.right > span.state-time</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='call-container']/div/div[5]/p/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=paragraph >> internal:text=&quot;0:10&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>27c7b98b-2622-4bce-b215-2a9b8a72c685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>state-time</value>
      <webElementGuid>a868e65c-916f-4a31-8745-7585c795ce8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0:10</value>
      <webElementGuid>8b670409-1118-4b22-83e3-8fadd9d4bdee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;call-container&quot;)/div[@class=&quot;call-contact-body-ui&quot;]/div[@class=&quot;contact-info&quot;]/p[@class=&quot;contact-state-info right&quot;]/span[@class=&quot;state-time&quot;]</value>
      <webElementGuid>335e6b55-ef4d-4c09-8fba-c86d8e6d12df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='call-container']/div/div[5]/p/span[2]</value>
      <webElementGuid>13378fb5-381b-4f0e-9f85-15446a61474f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dialing'])[3]/following::span[1]</value>
      <webElementGuid>2a297de7-41f3-473e-b765-71c012afb487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::span[4]</value>
      <webElementGuid>1256e982-3a88-498b-9d29-0472afc58868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outboundcalls_US (23053627)'])[3]/preceding::span[1]</value>
      <webElementGuid>9435c7bc-cde5-4687-a238-f43f109f385d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bad Number'])[1]/preceding::span[2]</value>
      <webElementGuid>96771eb8-c42e-4629-a042-b20dec7959fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/p/span[2]</value>
      <webElementGuid>b2005004-1d74-4a43-b4d4-62397f99c346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '0:10' or . = '0:10')]</value>
      <webElementGuid>2711eea0-45d6-46cd-8493-00f037cee91d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
