<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Voice Call</name>
   <tag></tag>
   <elementGuidId>08fca6b6-e2af-458b-833e-dd4e35beaf11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-2ftnr5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cx1_agent_root']/div[2]/div[2]/div/div[3]/div/div/section/div[2]/ul/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;flex-Display-bt&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cea94a9b-12e5-455f-9683-4b574ae683c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-2ftnr5</value>
      <webElementGuid>6c37f332-72cb-4d72-865a-f6437d8c16f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a3b84f0a-2977-40ee-b17a-a7945cb52a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d828b468-9a9e-495b-8c06-5a258642d850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>flex-Display-bt</value>
      <webElementGuid>a5d5981a-eb83-49c5-b5df-5bf832f36000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Voice Call</value>
      <webElementGuid>21f060dd-e1c6-49a8-b058-80aec680280b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@id=&quot;cx1_agent_root&quot;]/main[1]/div[@class=&quot;MuiBox-root css-1uq669f&quot;]/main[@class=&quot;MuiBox-root css-o3ihhy&quot;]/div[@id=&quot;cx1_agent_root&quot;]/div[@class=&quot;MuiBox-root css-19ku4tl&quot;]/div[@class=&quot;MuiBox-root css-13dfkjh&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-6sv6c4&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-1hu6jpd&quot;]/div[@class=&quot;MuiGrid-root css-q0m19r&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-sm-12 MuiGrid-grid-lg-12 css-1tgvtps&quot;]/section[@class=&quot;MuiBox-root css-10wd32q&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 css-etfqn7&quot;]/ul[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 css-17u66t0&quot;]/div[1]/div[@class=&quot;MuiBox-root css-1o9xcq9&quot;]/div[@class=&quot;MuiBox-root css-2ftnr5&quot;]</value>
      <webElementGuid>bd446498-7cf6-4fff-acf9-58d2de18a199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cx1_agent_root']/div[2]/div[2]/div/div[3]/div/div/section/div[2]/ul/div/div/div</value>
      <webElementGuid>05065a3b-53b8-49b6-ae57-59e6137826cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/following::div[3]</value>
      <webElementGuid>8239a13a-317c-4113-a9c1-eb41e28f0e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/div/div</value>
      <webElementGuid>94bc1970-4fe4-4286-8614-409666fb7802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Voice Call' or . = 'Voice Call')]</value>
      <webElementGuid>c232a587-ce8f-4863-944b-189aefef74b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cx1_agent_root']/div[2]/div[2]/div/div[3]/div/div/section/div[2]/ul/div/div/div/div[2]</value>
      <webElementGuid>801795e7-36ae-4d8a-956b-bade61b573e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/following::div[5]</value>
      <webElementGuid>6fb05233-6e19-46af-a9f0-863fb7002bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Voice Call']/parent::*</value>
      <webElementGuid>e314cdd2-7a52-4e62-b63e-3168862ce66d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/div/div/div[2]</value>
      <webElementGuid>35b1329b-5601-4402-a0f9-d90b4bdf7c16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
