<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_971554573936</name>
   <tag></tag>
   <elementGuidId>e1402600-6786-49e6-b715-390226211bc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mui-22']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tooltip[name=&quot;+971554573936&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1920ec3a-499b-4305-93b9-29ee5514e4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>e681563d-75a8-4c3f-9872-5c3317f0e46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-22</value>
      <webElementGuid>86728cb3-2741-4495-8e17-d3df6187f995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTooltip-popper MuiTooltip-popperInteractive MuiTooltip-popperArrow css-1xjiak MuiPopperUnstyled-root</value>
      <webElementGuid>5c5b9999-2da5-4cc7-92c9-9402d5efe8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popper-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>68bca5e1-ff1f-4173-afa2-490c249588b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+971554573936</value>
      <webElementGuid>5f0419c3-2203-4509-b6d3-13c2f867fc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-22&quot;)</value>
      <webElementGuid>2b57a53f-1a09-4d68-9a2d-9c29ee15e1fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mui-22']</value>
      <webElementGuid>e5801ad2-06ed-4cda-96f8-69aa34544533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>240631e5-50ed-4c58-9523-f9df69ad06db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mui-22' and (text() = '+971554573936' or . = '+971554573936')]</value>
      <webElementGuid>f615d9bc-e7a6-4f6d-9ef2-9d79c1a00236</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
