<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Outboundcalls_US</name>
   <tag></tag>
   <elementGuidId>091a5149-57a6-48a8-96c6-154006758c39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.MuiTypography-root.MuiTypography-inherit.css-1352336</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cx1_agent_root']/div[2]/div[2]/div/div/section/div/div[3]/div/div/div/div/div/div[2]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;interaction-cde6e638-2675-4655-bc75-3248697882b2&quot;] >> internal:text=&quot;Outboundcalls_US&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0092ba49-b52e-4a48-8855-93a98b37afc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-inherit css-1352336</value>
      <webElementGuid>56d7c406-0cb5-45b0-a208-6f8cde8cd77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outboundcalls_US</value>
      <webElementGuid>201d9e36-16e4-41e5-8aea-d57509d929c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@id=&quot;cx1_agent_root&quot;]/main[1]/div[@class=&quot;MuiBox-root css-1uq669f&quot;]/main[@class=&quot;MuiBox-root css-o3ihhy&quot;]/div[@id=&quot;cx1_agent_root&quot;]/div[@class=&quot;MuiBox-root css-19ku4tl&quot;]/div[@class=&quot;MuiBox-root css-13dfkjh&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-6sv6c4&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item css-1wxaqej&quot;]/section[@class=&quot;MuiBox-root css-19yj1du&quot;]/div[@class=&quot;MuiBox-root css-11x5kh1&quot;]/div[@class=&quot;noArrow
            false MuiBox-root css-1c8f6qt&quot;]/div[@class=&quot;interaction MuiBox-root css-0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root ccf-interaction css-1dgr6ct&quot;]/div[@class=&quot;MuiBox-root css-2yplm6&quot;]/div[@class=&quot;MuiBox-root css-7l26r7&quot;]/div[@class=&quot;css-ofo63b&quot;]/div[@class=&quot;MuiBox-root css-1xhj18k&quot;]/div[@class=&quot;MuiBox-root css-179ws4o&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-inherit css-1352336&quot;]</value>
      <webElementGuid>0ee50b8d-d103-4df0-b665-946191041411</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cx1_agent_root']/div[2]/div[2]/div/div/section/div/div[3]/div/div/div/div/div/div[2]/div/p</value>
      <webElementGuid>1fd7f91e-5494-4fd7-adfd-2f946eb5a4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dialed number is invalid'])[1]/following::p[2]</value>
      <webElementGuid>50c82dad-8a4a-42da-b749-6d6805dc5fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Outboundcalls_US']/parent::*</value>
      <webElementGuid>23035782-58c9-4757-97e7-2e760c23bcf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>1c40d771-41bf-40da-8395-6c90142b2c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Outboundcalls_US' or . = 'Outboundcalls_US')]</value>
      <webElementGuid>7a6447fa-93aa-430d-ac0d-8fe083ce7c45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
