<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect</name>
   <tag></tag>
   <elementGuidId>694e1e9e-87a8-42d6-b9cc-ad485d91a0bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Group_118160 > #Group_118158 > #Rectangle_80239 > rect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Directory&quot;i >> rect >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>ff0f57de-cba2-402f-980f-537312ccf2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20.212</value>
      <webElementGuid>13ed42d7-af59-49d4-8171-982ff05aa945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>19.997</value>
      <webElementGuid>39e92d32-3313-4027-96a2-64036e3314f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>189a6c59-d9da-43bf-8d1b-7eae727096a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Group_118160&quot;)/g[@id=&quot;Group_118158&quot;]/g[@id=&quot;Rectangle_80239&quot;]/rect[1]</value>
      <webElementGuid>7bf738af-3cd5-46cd-ab95-ad9a26fd94cb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
