<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Voice Call</name>
   <tag></tag>
   <elementGuidId>00b0d94a-da65-4304-8716-2c8a42f37f5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-2ftnr5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cx1_agent_root']/div[2]/div[2]/div/div[3]/div/div/section/div[2]/ul/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;flex-Display-bt&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ee9fc034-2903-42fa-8a52-9df1b6825fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-2ftnr5</value>
      <webElementGuid>3a051d32-36e8-4741-b848-762c90624c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1f0851da-fb28-4258-928b-04947c1464a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>124b4486-e9a3-4a7c-a1e8-cc51e1249c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>flex-Display-bt</value>
      <webElementGuid>f38c09ce-cdbf-4688-ae68-8c62701fdddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Voice Call</value>
      <webElementGuid>de6af72a-a34b-4403-8872-daa52938a900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@id=&quot;cx1_agent_root&quot;]/main[1]/div[@class=&quot;MuiBox-root css-1uq669f&quot;]/main[@class=&quot;MuiBox-root css-o3ihhy&quot;]/div[@id=&quot;cx1_agent_root&quot;]/div[@class=&quot;MuiBox-root css-19ku4tl&quot;]/div[@class=&quot;MuiBox-root css-13dfkjh&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-6sv6c4&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-1hu6jpd&quot;]/div[@class=&quot;MuiGrid-root css-q0m19r&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-sm-12 MuiGrid-grid-lg-12 css-1tgvtps&quot;]/section[@class=&quot;MuiBox-root css-10wd32q&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 css-etfqn7&quot;]/ul[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 css-17u66t0&quot;]/div[1]/div[@class=&quot;MuiBox-root css-1o9xcq9&quot;]/div[@class=&quot;MuiBox-root css-2ftnr5&quot;]</value>
      <webElementGuid>8dd0b8d0-e1db-49b0-a904-9d3a258153ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cx1_agent_root']/div[2]/div[2]/div/div[3]/div/div/section/div[2]/ul/div/div/div</value>
      <webElementGuid>a48ec673-ba38-4909-b634-bbf436c71b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/following::div[3]</value>
      <webElementGuid>6c21e630-d2bd-435e-98a3-b4d5e4485a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/div/div</value>
      <webElementGuid>d406b484-e30e-4b70-b9f5-77d8eae30947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Voice Call' or . = 'Voice Call')]</value>
      <webElementGuid>a3352b20-4c30-4431-aba8-55faf951d74e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
