<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__searchField</name>
   <tag></tag>
   <elementGuidId>29ce4997-fd9f-44a9-b40a-2d446701a486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;search-directory&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45405576-d33e-42b1-aa8b-ccae53914cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2817bbc6-48fb-4ecc-a94f-6c6f0481c352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7f575ea3-1459-4eb1-ac3a-17c6e0a849ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchField</value>
      <webElementGuid>f12d8395-dbac-4934-beb6-de85d4303ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for people, skills, teams, etc.</value>
      <webElementGuid>2a6408b0-5c01-43c4-9b06-976f9a753558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebe34984-edf0-4b0c-8eab-23ccb7274198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>search-directory</value>
      <webElementGuid>ba29619d-4569-43fd-a2b1-e8700f92ed68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall MuiInputBase-inputAdornedStart css-162edyi</value>
      <webElementGuid>d684414d-35c2-4602-8296-90413b5e0e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchField&quot;)</value>
      <webElementGuid>76969dc0-7431-4c6a-aca0-25bb195ca5ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchField']</value>
      <webElementGuid>93d048ee-0cdd-4728-b7ea-b99d939ed09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cx1_agent_root']/div[2]/div[2]/div/div[3]/div/div/section/div[2]/div[2]/div/div/input</value>
      <webElementGuid>b0119dca-1140-4253-a583-6af672611af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4b51c844-fc4c-4357-934c-73c6be870e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchField' and @placeholder = 'Search for people, skills, teams, etc.' and @type = 'text']</value>
      <webElementGuid>4b384ef9-b152-4983-924d-01590161cacf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
